export const tableOption = {
    dialogDrag: false,
    dialogWidth: 420,
    labelWidth: 76,
    border: true,
    index: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    menuWidth: 0,
    menu: false,
    align: 'left',
    viewBtn: false,
    excelBtn: false,
    addBtn: false,
    delBtn: false,
    editBtn: false,
    columnBtn: false,
    printBtn: false,
    menuType: 'text',
    searchMenuSpan: 6,
    searchShow: true,
    searchIndex: 3,
    searchIcon: true,
    selection: true,
    size:'mini',
    column: [
        {
            label: 'C段',
            prop: 'cidr_ip',
            search: true,
            span: 24,
            slot:true,
        },
        {
            label: 'IP数',
            prop: 'ip_count',
            span: 12,
            search: false,
            align:'center',
            slot:true,
            width:200,
        },
        {
            label: '域名数',
            prop: 'domain_count',
            search:false,
            span: 12,
            width:200,
            align:'center',
        },
    ]
}