export const tableOption = {
    dialogDrag: false,
    dialogWidth: 420,
    labelWidth: 76,
    border: true,
    index: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    menuWidth: 0,
    menu: false,
    align: 'left',
    viewBtn: false,
    excelBtn: false,
    addBtn: false,
    delBtn: false,
    editBtn: false,
    columnBtn: false,
    printBtn: false,
    menuType: 'text',
    searchMenuSpan: 6,
    searchShow: true,
    searchIndex: 3,
    searchIcon: true,
    selection: true,
    size:'mini',
    column: [
        {
            label: 'URL',
            prop: 'url',
            search: true,
            span: 24,
            slot:true,
        },
        {
            label: '标题',
            prop: 'title',
            span: 12,
            search: true,
            slot:true,
        },
        {
            label: '状态码',
            prop: 'status_code',
            search:true,
            span: 12,
        },
        {
            label: 'body长度',
            prop: 'content_length',
            search:true,
            searchPlaceholder:'请输入body 长度进行搜索',
            span: 12,
        },

    ]
}