export const tableOption = {
    dialogDrag: false,
    dialogWidth: 420,
    labelWidth: 76,
    border: true,
    index: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    menuWidth: 0,
    menu: false,
    align: 'left',
    viewBtn: false,
    excelBtn: false,
    addBtn: false,
    delBtn: false,
    editBtn: false,
    columnBtn: false,
    printBtn: false,
    menuType: 'text',
    searchMenuSpan: 6,
    searchShow: true,
    searchIndex: 3,
    searchIcon: true,
    selection: true,
    size:'mini',
    column: [
        {
            label: '协议',
            prop: 'scheme',
            search: true,
            span: 24,
            slot:true,
        },
        {
            label: '主机',
            prop: 'host',
            span: 12,
            search: true,
            slot:true,
        },
        {
            label: '端口',
            prop: 'port',
            search:true,
            span: 12,
        },
        {
            label: '目标',
            prop: 'target',
            search:true,
            span: 12,
        },
        {
            label: '保存时间',
            prop: 'date',
            span: 12,
        },

    ]
}