export const tableOption = {
    dialogDrag: false,
    dialogWidth: 420,
    labelWidth: 76,
    border: true,
    index: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    menuWidth: 0,
    menu: false,
    align: 'left',
    viewBtn: false,
    excelBtn: false,
    addBtn: false,
    delBtn: false,
    editBtn: false,
    columnBtn: false,
    printBtn: false,
    menuType: 'text',
    searchMenuSpan: 6,
    searchShow: true,
    searchIndex: 3,
    searchIcon: true,
    selection: true,
    size: 'mini',
    column: [
        {
            label: '模版ID',
            prop: 'template_id',
            search: true,
            span: 24,
            slot: true,
            width: 140,
        },
        {
            label: '目标',
            prop: 'target',
            span: 12,
            search: true,
            width: 200,
            slot: true,
        },
        {
            label: '漏洞URL',
            prop: 'vuln_url',
            search: true,
            width: 300,
            span: 12,
        },
        {
            label: '漏洞名称',
            prop: 'vuln_name',
            search: true,
            width: 280,
            span: 12,
        },
        {
            label: '漏洞等级',
            prop: 'vuln_severity',
            span: 12,
            width: 90,
            align: 'center',
        },
        {
            label: '保存时间',
            prop: 'save_date',
            width: 90,
            align: 'center',
            span: 12,
        },
        {
            label: '验证命令',
            prop: 'curl_command',
            span: 12,
            width: 300,
            fixed: 'right'
        },

    ]
}