export const tableOption = {
    dialogDrag: false,
    dialogWidth: 420,
    labelWidth: 76,
    border: true,
    index: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    menuWidth: 0,
    menu: false,
    align: 'left',
    viewBtn: false,
    excelBtn: false,
    addBtn: false,
    delBtn: false,
    editBtn: false,
    columnBtn: false,
    printBtn: false,
    menuType: 'text',
    searchMenuSpan: 6,
    searchShow: true,
    searchIndex: 3,
    searchIcon: true,
    selection: true,
    size:'mini',
    column: [
        {
            label: '服务',
            prop: 'service_name',
            headerAlign:'center',
            search: true,
            span: 24,
        },
        {
            label: 'IP端口',
            prop: 'info',
            headerAlign:'center',
            span: 12,
            slot:true,
        },
        {
            label: 'IP',
            prop: 'service_info.ip',
            search:true,
            hide:true,
            span: 12,
        },
        {
            label: '端口',
            prop: 'service_info.port_id',
            search:true,
            hide:true,
            span: 12,
        },
        {
            label: '产品',
            prop: 'service_info.product',
            search:true,
            headerAlign:'center',
            align:'center',
            span: 12,
            slot:true,
        },
    ]
}